name: db_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  floor: ^1.5.0
  sqflite: ^2.4.1 
  # path: ^1.8.0

# dart run build_runner build -d --delete-conflicting-outputs
dev_dependencies:
  floor_generator: ^1.5.0
  build_runner: ^2.4.13
  lints: ^4.0.0
  test: ^1.24.0
